-- Disable foreign key checks during drop
DROP TABLE IF EXISTS BALANCE CASCADE;
DROP TABLE IF EXISTS course_progress CASCADE;
DROP TABLE IF EXISTS RESULT CASCADE;
DROP TABLE IF EXISTS QUESTIONS CASCADE;
DROP TABLE IF EXISTS chapters CASCADE;
DROP TABLE IF EXISTS ENROLLMENT CASCADE;
DROP TABLE IF EXISTS COURSES CASCADE;
DROP TABLE IF EXISTS Instituate CASCADE;
DROP TABLE IF EXISTS USERS CASCADE;

CREATE TABLE USERS (
    user_id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    join_date DATE DEFAULT CURRENT_DATE
);

CREATE TABLE Instituate (
    user_id INT PRIMARY KEY REFERENCES USERS(user_id) ON DELETE CASCADE
);

CREATE TABLE COURSES (
    COURSE_ID SERIAL PRIMARY KEY,
    COURSE_TITLE VARCHAR(255) NOT NULL,
    COURSE_PRICE NUMERIC NOT NULL,
    USER_ID INT REFERENCES USERS(user_id) ON DELETE CASCADE,
    JOIN_DATE DATE DEFAULT CURRENT_DATE
);

CREATE TABLE chapters (
    CHAPTER_ID SERIAL PRIMARY KEY,
    chapter_title VARCHAR(255) NOT NULL,
    CHAPTER_DESCRIPTION TEXT,
    CHAPTER_VIDEO VARCHAR(255),
    CHAPTER_NOTES VARCHAR(255),
    COURSE_ID INT REFERENCES COURSES(COURSE_ID) ON DELETE CASCADE
);

CREATE TABLE QUESTIONS (
    QUESTION_ID SERIAL PRIMARY KEY,
    QUESTION_TEXT TEXT NOT NULL,
    OPTIONA VARCHAR(255) NOT NULL,
    OPTIONB VARCHAR(255) NOT NULL,
    OPTIONC VARCHAR(255) NOT NULL,
    OPTIOND VARCHAR(255) NOT NULL,
    ANSWER VARCHAR(255) NOT NULL,
    COURSE_ID INT REFERENCES COURSES(COURSE_ID) ON DELETE CASCADE
);

CREATE TABLE ENROLLMENT (
    user_id INT REFERENCES USERS(user_id) ON DELETE CASCADE,
    course_id INT REFERENCES COURSES(COURSE_ID) ON DELETE CASCADE,
    PRIMARY KEY(user_id, course_id)
);

CREATE TABLE course_progress (
    USER_ID INT REFERENCES USERS(user_id) ON DELETE CASCADE,
    COURSE_ID INT REFERENCES COURSES(COURSE_ID) ON DELETE CASCADE,
    CHAPTER_ID INT REFERENCES chapters(CHAPTER_ID) ON DELETE CASCADE,
    IS_COMPLETED BOOLEAN DEFAULT FALSE,
    PRIMARY KEY(USER_ID, COURSE_ID, CHAPTER_ID)
);

CREATE TABLE RESULT (
    USER_ID INT REFERENCES USERS(user_id) ON DELETE CASCADE,
    COURSE_ID INT REFERENCES COURSES(COURSE_ID) ON DELETE CASCADE,
    SCORE INT NOT NULL,
    completion_date DATE DEFAULT CURRENT_DATE,
    PRIMARY KEY(USER_ID, COURSE_ID)
);

CREATE TABLE BALANCE (
    user_id INT REFERENCES USERS(user_id) ON DELETE CASCADE,
    amount NUMERIC DEFAULT 0,
    PRIMARY KEY(user_id)
);
